# eks-app.yaml
apiVersion: v1
kind: Service   
metadata:
  name: eks-app-service
  annotations:
  service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing    
  service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
  service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  labels:
    app.kubernetes.io/name: eks-app
    app.kubernetes.io/instance: eks-app
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    app.kubernetes.io/name: eks-app
    app.kubernetes.io/instance: eks-app
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app
    spec:
      containers:
      - name: eks-app-container
        image: 676206915500.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:ccf987b90f3d50b7b7e4709949619db4d1794732
        volumeMounts:
        - name: empty-dir
          mountPatch: /mount
        ports:
          - protocol: TCP
            containerPort: 8080
      volumes:
        - emptyDir: {}
          name: empty-dir
      
