# eks-app.yaml
apiVersion: v1
kind: Service   
metadata:
  name: eks-app-service
spec:
  selector:
    app.kubernetes.io/name: eks-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app
    spec:
      containers:
      - name: eks-app-container
        image: 676206915500.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:ccf987b90f3d50b7b7e4709949619db4d1794732
        ports:
          - protocol: TCP
            containerPort: 8080
